trigger:
- main

pool:
  name: 'Default'

variables:
  BUILD_CONFIGURATION: 'Release'
  NUGET_SOURCE: 'https://pkgs.dev.azure.com/rmohsin0787/StringExtensionLibrary/_packaging/MyFeed/nuget/v3/index.json'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Install .NET SDK'

# Restore Dependencies
- script: dotnet restore
  displayName: 'Restore Dependencies'

# Build the Class Library
- script: dotnet build --configuration $(BUILD_CONFIGURATION)
  displayName: 'Build Class Library'

# Pack the Class Library into a NuGet Package
- script: dotnet pack --configuration $(BUILD_CONFIGURATION) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

# Debugging: Check the output directory
- script: echo $(Build.ArtifactStagingDirectory)
  displayName: 'Print Artifact Staging Directory'

- script: dir $(Build.ArtifactStagingDirectory)
  displayName: 'List Files in Artifact Staging Directory'

# Publish Pipeline Artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'MyFeed'
    publishLocation: 'pipeline'
  displayName: 'Publish Pipeline Artifact'
